---
booktitle: Proceedings of the Conference on Health, Inference, and Learning
shortname: CHIL
volume: '174'
year: '2022'
start: 2022-04-07
end: 2022-04-08
published: 2022-04-06
conference_number: '3'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: CHIL-2022
month: 0
cycles: false
bibtex_editor: Flores, Gerardo and Chen, George H and Pollard, Tom and Ho, Joyce C
  and Naumann, Tristan
editor:
- given: Gerardo
  family: Flores
- given: George H
  family: Chen
- given: Tom
  family: Pollard
- given: Joyce C
  family: Ho
- given: Tristan
  family: Naumann
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Conference on Health, Inference, and Learning
    Held in Virtual on 07-08 April 2022

  Published as Volume 174 by the Proceedings of Machine Learning Research on 06 April 2022.

  Volume Edited by:
    Gerardo Flores
    George H Chen
    Tom Pollard
    Joyce C Ho
    Tristan Naumann

  Series Editors:
    Neil D. Lawrence
date_str: 07--08 Apr
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v174"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v174
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v174
email: ''
conference:
  name: Conference on Health, Inference, and Learning
  url: https://www.chilconference.org/
  location: Virtual
  dates:
  - 2022-04-07
  - 2022-04-08
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/home/markus/repos/mlresearch/v174/CHIL2022.bib"
# Site settings
# Original source:  /home/markus/repos/mlresearch/v174/CHIL2022.bib
